FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Install the required packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the API script
COPY . .

# Expose the port that the API script will run on
EXPOSE 80

# Run the API script
CMD ["python", "ListaP.py"]